services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "443:443/tcp"
    environment:
      TZ: "Asia/Manila"
      WEBPASSWORD: ""
      PIHOLE_DNS_: "127.0.0.1#5353;8.8.8.8#53"
      DNSMASQ_LISTENING: "all"
    volumes:
      - ~/docker/pihole/etc-pihole:/etc/pihole
      - ~/docker/pihole/etc-dnsmasq:/etc/dnsmasq>
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"